# Stage 1: Build stage
FROM python:3.11-alpine AS build

# Set working directory
WORKDIR /my_dir

# Copy only necessary files for installing dependencies
COPY requirements.txt .

# Install build dependencies for Python packages
RUN apk add --no-cache --virtual .build-deps \
       gcc \
       musl-dev \
       libffi-dev \
       openssl-dev && \
    pip install --no-cache-dir -r requirements.txt && \
    apk del .build-deps  # Remove build dependencies to save space

# Copy the rest of the application
COPY . .

# Stage 2: Final stage
FROM python:3.11-alpine

# Set working directory
WORKDIR /my_dir

# Copy the application from the build stage
COPY --from=build /my_dir /my_dir

# Expose port
EXPOSE 80

# Set environment variable
ENV MY_STRING my_env_string

# Command to run the application
CMD ["python", "test.py"]
