FROM python:3.11-alpine

WORKDIR /my_dir

RUN apk add --no-cache --virtual .build-deps \
    gcc \
    musl-dev \
    python3-dev \
    linux-headers \
    && apk del .build-deps \
    && rm -rf /root/.cache/pip/*

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . /my_dir

CMD ["python", "test.py"]